---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ziyanetw/dataweb/erapor/
    - /bin/cp -R * $DEPLOYPATH
    - /opt/cpanel/composer/bin/composer install
    - /bin/php artisan key:generate
    - /bin/php artisan migrate
    - /bin/php artisan db:seed
